

# POST http://localhost:3000/get-blog
# Content-Type: application/json

# {
#     "blog_id": "Testing-onemqpubz5HSPyu-51oI8iGk"
# }

POST http://localhost:3000/get-profile
Content-Type: application/json

{
    "username": "sunguard9509"
}


# POST http://localhost:3000/search-users
# Content-Type: application/json

# {
#     "username": "taeyang"
# }